### ISSUE TITLE
The epoch timer seems to be stuck at end of epoch and doesn't update automatically and the page needs to be refreshed when epoch has active nominations

### ISSUE THREAD

**Issue by cpuja84** [vegaprotocol/token-frontend#825] opened 2021-11-15 23:05 UTC
The epoch timer seems to be stuck at end of epoch and doesn't update automatically and the page needs to be refreshed.
This seems to be happening only when you have active nominations for the epoch and you stay on the nomination page after nominating to a validator. If you move away from the page after nominating, then the user doesn't experinece this issue.

<img width="1156" alt="Screenshot 2021-11-15 at 15 04 06" src="https://user-images.githubusercontent.com/69709857/141866669-d47220ca-53e8-4b2e-afbf-a55749239173.png">

<img width="1349" alt="Screenshot 2021-11-15 at 14 54 29" src="https://user-images.githubusercontent.com/69709857/141866698-b3436676-2ff3-46df-8717-e59d322b6539.png">

**Comment by campbellssource** [comment] 2021-11-17 09:45
@cpuja84 we can't reproduce this. bumping it down the list for now

**Comment by dexturr** [comment] 2021-11-26 13:13
In light of #942 I think we can close this, as it appears to be working.

Feel free to reopen if I am incorrect :+1:

**Closed by dexturr** 2021-11-26 13:13 UTC
Labels: bug

**Comment by cpuja84** [comment] 2021-11-26 13:29
Yes @dexturr, this issue no longer exists and can be closed
