### ISSUE TITLE
Rewards query fails on token.fairground.wtf

### ISSUE THREAD

**Issue by cdm** [vegaprotocol/token-frontend#1020] opened 2021-12-01 15:26 UTC
Since the release of the update for Fairground token front end earlier today, we're seeing a 422 / GraphQL query error when navigating to the Rewards tab with a Vega wallet connected.

<img width="951" alt="Screenshot 2021-12-01 at 15 22 50" src="https://user-images.githubusercontent.com/149245/144262514-d245d843-201b-4c9d-9de1-df1485106c1b.png">

https://token.fairground.wtf/rewards

```
query Rewards($partyId: ID!) {
  party(id: $partyId) {
    id
    rewardDetails {
      asset {
        id
        symbol
        __typename
      }
      rewards {
        assetId
        partyId
        epoch
        amount
        percentageOfTotal
        receivedAt
        __typename
      }
      totalAmount
      __typename
    }
    delegations {
      amount
      epoch
      __typename
    }
    __typename
  }
  epoch {
    id
    timestamps {
      start
      end
      expiry
      __typename
    }
    __typename
  }
}

```

**Comment by dexturr** [comment] 2021-12-01 15:29
Closing as duplicate of #1006, addressed in #1010 

Thanks for the detailed report :pray:

**Closed by dexturr** 2021-12-01 15:29 UTC
