### ISSUE TITLE
Inconsistency in messages to connect to a wallet

### ISSUE THREAD

**Issue by pgriscti** [vegaprotocol/token-frontend#906] opened 2021-11-19 09:30 UTC
<img width="1352" alt="Screenshot 2021-11-19 at 09 24 49" src="https://user-images.githubusercontent.com/7977128/142599312-7e5caca8-4819-4345-b389-f1e4d27eef7f.png">

**Comment by campbellssource** [comment] 2021-11-19 17:13
duplicate of #917

**Closed by campbellssource** 2021-11-19 17:13 UTC
Labels: Design needed
