### ISSUE TITLE
Bug: validator list on staking tab not shown if you don't connect a Vega wallet

### ISSUE THREAD

**Issue by barnabee** [vegaprotocol/token-frontend#940] opened 2021-11-22 23:33 UTC
# Bug report

## Describe the bug

On the current deploy preview when I go to https://6196adb6fba4700008870dfc--token-vega-xyz.netlify.app/staking I cannot see who the validators are or how much stake they each have without connecting a Vega wallet. This is a problem because most visitors to this site probably won't have a wallet. 

## Environement

Firefox / Mac

## To Reproduce

Go to https://6196adb6fba4700008870dfc--token-vega-xyz.netlify.app/staking

## Expected behavior

I'd expect to see all the valdiators and their stake but instead get loads of errors and requests to connect wallets even though they aren't needed to show this info.

## Screenshots

<img width="847" alt="image" src="https://user-images.githubusercontent.com/1179257/142950075-14b8bd1e-9e79-4369-97c6-2ce8bf1a67d0.png">

## ETH Wallet software:

Metamask / Frame (but I am not expecting to need to connect them at this point)

## Vega Wallet software version:

0.10.0 but I am not expecting to need to connect it at this point.

## Run the following GQL query on the playground above (depending on the env you are using):

Not relevant, I am using the site without a wallet.

### Result:

No way to see basic and important public info without connecitng a wallet.

## Additional context

In general the site is too pushy for wallet connections IMO. If Metamask has been connected in the past it shouldn't be required to be unlocked to see any page, etc. even if that is needed to see data related to your wallet or actions you can take, similarly we shouldn't be hiding really important network info that needs to be public like the validators and their stake from people who aren't "logged in".

**Comment by mattrussell36** [comment] 2021-11-23 01:32
Closing as dupe of https://github.com/vegaprotocol/token-frontend/issues/921.

This has been done and will be on staging very shortly

**Closed by mattrussell36** 2021-11-23 01:32 UTC
Labels: bug
