### ISSUE TITLE
Full screen error message if site is unable to connect to network

### ISSUE THREAD

**Issue by campbellssource** [vegaprotocol/token-frontend#1075] opened 2021-12-13 16:24 UTC
<img width="752" alt="Screenshot 2021-12-13 at 16 24 47" src="https://user-images.githubusercontent.com/13255539/145849863-a24565e7-02af-4414-9757-91c5ecf22d8d.png">

If the site is unable to connect to the Vega network...
example conditions....
- 422 error
- block height 0
- chain status != active
 
Show a message and give the user an option to connect to a different node
- free text input for the node address for now...
...eventually a node discovery service could be used, as well the option 

History in here #297 

- [ ] This also requires the user to be able to see what node they are connected to and to change it. but this is possibly blocked by https://github.com/vegaprotocol/token-frontend/issues/931
- [ ] Clean the input client side
- [ ] submitting the form re-starts the loading spinner... if the new node does not work then it'll return to the error state

- [ ] Do we want to use the config in a connected wallet (once connected)
<img width="417" alt="Screenshot 2021-12-13 at 16 46 49" src="https://user-images.githubusercontent.com/13255539/145853601-ea9ac832-913b-4edf-972e-96d6df93af8c.png">
This would allow the user to select from a list of known good addresses as well as input their own.

test via overriding local storage data

**Comment by gordsport** [comment] 2022-05-31 21:02
closing as dupe of:
- https://github.com/vegaprotocol/frontend-monorepo/issues/6

**Closed by gordsport** 2022-05-31 21:02 UTC
Labels: Feature 💫💫, Token Frontend
